add_newline = false
command_timeout = 2000

[container]
disabled = true

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[sudo]
style = 'bold green'
symbol = 'su '
disabled = false

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
